### ISSUE TITLE
Release of version 2.0.0

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#648]
Nice! Here it is version 2.0.0 After the first release of PLexrequests.net on 13 March  i'd like to discuss what to implement in the next 2.0 version.

I have make already a selection if what users like to have. Do you have a great idea to? post it over here.

- [ ] Big improvements on the core business of plexrequest:  the request pages for tv shows and movies (https://github.com/tidusjar/PlexRequests.Net/issues/163 https://github.com/tidusjar/PlexRequests.Net/issues/169 https://github.com/tidusjar/PlexRequests.Net/issues/175 https://github.com/tidusjar/PlexRequests.Net/issues/490 https://github.com/tidusjar/PlexRequests.Net/issues/136 https://github.com/tidusjar/PlexRequests.Net/issues/324 https://github.com/tidusjar/PlexRequests.Net/issues/460 https://github.com/tidusjar/PlexRequests.Net/issues/211 https://github.com/tidusjar/PlexRequests.Net/issues/607 https://github.com/tidusjar/PlexRequests.Net/issues/637)
- [ ] Overall improvements in visibility (https://github.com/tidusjar/PlexRequests.Net/issues/265 https://github.com/tidusjar/PlexRequests.Net/issues/582 https://github.com/tidusjar/PlexRequests.Net/issues/111)
- [ ] Big improvements on the notifications system (https://github.com/tidusjar/PlexRequests.Net/issues/60  https://github.com/tidusjar/PlexRequests.Net/issues/261 https://github.com/tidusjar/PlexRequests.Net/issues/279 https://github.com/tidusjar/PlexRequests.Net/issues/611)

**Comment by leram84** [comment]
I have some thoughts for usermanager, but not sure what is applicable (depending on what features you add to it). But I feel like a full "my account" tab would be useful. Inside you would get 

* settings (change email, add other notification channels, choose how to be notified for each thing, etc)
* My requests (this way you wouldn't have to use email notifications at all if you don't want to, just go here to see what's been fulfilled) 
* My issues (see past issues of yours that have been resolved, also something that could use notifications)
* messages (i know you dont think this fits right now, and i kind of agree (until you change the name of this app ;) ) but if you ever do add this feature, this would be the place to include it.)

**Comment by tidusjar** [comment]
The my account part is not part of the user management. It was going to be a separate piece of work as I can deliver them independently. But you have some good ideas there.
